basdat/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include,path
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ungu.urls')),
    path('', include('hijau.urls')),
    path('', include('konsultasicabang.urls')),
    path('', include('transaksi.urls'))
]

konsultasicabang/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from konsultasicabang.views import konsultasi, updatekonsultasi, rscabang, updaterscabang, daftarrscabang, daftarkonsultasi

app_name = 'konsultasicabang'

urlpatterns = [
    path('', views.loginregister, name='loginregister'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('administrator/', views.administrator, name='administrator'),
    path('dokter/', views.dokter, name='dokter'),
    path('pasien/', views.pasien, name='pasien'),
    path('logout/', views.logout, name='logout'),

    path('konsultasi/', views.konsultasi, name='konsultasi'),
    path('updatekonsultasi/<id>', views.updatekonsultasi, name='updatekonsultasi'),
    path('daftarkonsultasi/', views.daftarkonsultasi, name='daftarkonsultasi'),
    path('deletekonsultasi/<id>', views.deletekonsultasi, name='deletekonsultasi'),
    path('updatekonsultasi/updatekonsultasi/daftarkonsultasi/', views.daftarkonsultasi, name='daftarkonsultasi'),
    
    path('rscabang/', views.rscabang, name='rscabang'),
    path('updaterscabang/<id>', views.updaterscabang, name='updaterscabang'),
    path('daftarrscabang/', views.daftarrscabang, name='daftarrscabang'),
    path('deleterscabang/<id>', views.deleterscabang, name='deleterscabang'),
    path('updaterscabang/updaterscabang/daftarrscabang/', views.daftarrscabang, name='daftarrscabang'),

    # path('/homepagepasien/', views.hppasien, name='hppasien'),
    # path('/homepagedokter/', views.hpdokter, name='hpdokter'),
    # path('/homepageadmin/', views.hpadmin, name='hpadmin'),
]

ungu/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('daftar-dokter-rs-cabang', views.daftardokterrs, name='daftarDokterRs'),

    path('rud-dokter-rs', views.rudDokterRs, name='rudDokterRs'),
    path('rud-dokter-rs-admin', views.rudDokterRsAdmin, name='rudDokterRsAdmin'),
    path('dok-rs/update', views.dokRsUpdate, name='dokRsUpdate'),
    path('dok-rs/delete', views.dokRsDelete, name='dokRsDelete'),


    path('layanan-jadwal-poli', views.layananJadwalPoli, name='layananJadwalPoli'),
    path('layanan-jadwal-poli-admin', views.layananJadwalPoliAdmin, name='layananJadwalPoliAdmin'),
    path('orderPoli/pesan', views.orderPoli, name='orderPoli'),
    path('orderPoli-admin/pesan', views.orderPoliAdmin, name='orderPoliAdmin'),
    path('poli/update', views.updateLayananPoliklinik, name='updateLayananPoliklinik'),
    path('poli/delete', views.deleteLayananPoliklinik, name='deleteLayananPoliklinik'),
    path('orderPoli-admin/jadwal/update', views.updateJadwalPoliklinik, name='updateJadwalPoliklinik'),
    path('orderPoli-admin/jadwal/delete', views.deleteJadwalPoliklinik, name='deleteJadwalPoliklinik')
]

konsultasicabang/forms.py
from django import forms
from django.forms import widgets
from .models import Konsultasi, RSCabang, Administrator, Dokter, Pasien, Login
import datetime

class KonsultasiForm(forms.ModelForm):
    no_rekam_medis_pasien = forms.CharField(required=True)
    tanggal = forms.DateField(initial=datetime.date.today)
    id_transaksi = forms.CharField(required=True)

    class Meta:
        model = Konsultasi
        fields = {
            'no_rekam_medis_pasien',
            'tanggal',
            'id_transaksi'
        }
      

class UpdateKonsultasiForm(forms.ModelForm):
    tanggal = forms.DateField(initial=datetime.date.today, required=False)
    status = forms.CharField(required=False)
    class Meta:
            model = Konsultasi
            fields = {
                'tanggal',
                'status'
            } 
        
class RSCabangForm(forms.ModelForm):
        kode_rs = forms.CharField(required=True)
        nama = forms.CharField(required=True)
        tanggal_pendirian = forms.CharField(required=True)
        jalan = forms.CharField(required=False)
        nomor = forms.CharField(required=False)
        kota = forms.CharField(required=True)
        
        class Meta:
            model = RSCabang
            fields = {
                'kode_rs',
                'nama',
                'tanggal_pendirian',
                'jalan',
                'nomor',
                'kota' 
            } 

class UpdateRSCabangForm(forms.ModelForm):
        nama = forms.CharField(required=False)
        tanggal_pendirian = forms.CharField(required=False)
        jalan = forms.CharField(required=False)
        nomor = forms.CharField(required=False)
        kota = forms.CharField(required=False)

        class Meta:
            model = RSCabang
            fields = {
                'nama',
                'tanggal_pendirian',
                'jalan',
                'nomor',
                'kota' 
            }

class AdministratorForm(forms.ModelForm):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)
    nomor_identitas = forms.CharField(required=True)
    nama_lengkap = forms.CharField(required=True)
    tanggal_lahir = forms.CharField(required=True)
    email = forms.CharField(required=True)
    alamat = forms.CharField(required=True)
    
    class Meta:
            model = Administrator
            fields = {
                'username',
                'password',
                'nomor_identitas',
                'nama_lengkap',
                'tanggal_lahir',
                'email',
                'alamat' 
            }

class DokterForm(forms.ModelForm):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)
    nomor_identitas = forms.CharField(required=True)
    nama_lengkap = forms.CharField(required=True)
    tanggal_lahir = forms.CharField(required=True)
    email = forms.CharField(required=True)
    alamat = forms.CharField(required=True)
    no_SIP = forms.CharField(required=True)
    spesialisasi = forms.CharField(required=True)

    class Meta:
            model = Dokter
            fields = {
                'username',
                'password',
                'nomor_identitas',
                'nama_lengkap',
                'tanggal_lahir',
                'email',
                'alamat',
                'no_SIP',
                'spesialisasi' 
            }

class PasienForm(forms.ModelForm):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)
    nomor_identitas = forms.CharField(required=True)
    nama_lengkap = forms.CharField(required=True)
    tanggal_lahir = forms.CharField(required=True)
    email = forms.CharField(required=True)
    alamat = forms.CharField(required=True)
    alergi = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
            model = Pasien
            fields = {
                'username',
                'password',
                'nomor_identitas',
                'nama_lengkap',
                'tanggal_lahir',
                'email',
                'alamat',
                'alergi'
            }

class LoginForm(forms.ModelForm):
    email = forms.CharField(required=True)
    password = forms.CharField(required=True) 

konsultasicabang/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import Konsultasi, RSCabang, Administrator, Dokter, Pasien
from . import forms
from .forms import KonsultasiForm, RSCabangForm, UpdateKonsultasiForm, UpdateRSCabangForm, AdministratorForm, DokterForm, PasienForm, LoginForm
from django.contrib.auth import authenticate
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import login as auth_login
from django.contrib import messages

from django.db import connection
from collections import namedtuple

import random
# Create your views here.

def namedtuplefetchall(cursor):
    # "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]


def konsultasi(request):
    if (request.method == 'GET'):
        cursor1 = connection.cursor()
        cursor2 = connection.cursor()
        cursor1.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor2.execute('SET SEARCH_PATH TO MEDIKAGO;')
        choose_NRM = 'SELECT no_rekam_medis_pasien FROM SESI_KONSULTASI;'
        choose_IDT = 'SELECT id_transaksi FROM SESI_KONSULTASI;'

        cursor1.execute(choose_NRM)
        cursor2.execute(choose_IDT)
        data1 = namedtuplefetchall(cursor1)
        data2 = namedtuplefetchall(cursor2)

        form = KonsultasiForm(request.POST)
        listform = Konsultasi.objects.all()
        context = {
            'form' : form,
            'listform' : listform,
            'data1' : data1,
            'data2' : data2,
        }
        return render(request, 'konsultasi.html', context)

    elif (request.method == 'POST'):
        cursor_post = connection.cursor()
        no_rekam_medis_pasien = request.POST["no_rekam_medis_pasien"]
        tanggal = request.POST.get('tanggal')
        biaya = 0
        status = "Booked"
        id_transaksi = request.POST["id_transaksi"]

        cursor_post.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_post.execute("SELECT id_konsultasi FROM SESI_KONSULTASI ORDER BY id_konsultasi LIMIT 1;")
        temp_id_konsultasi = cursor_post.fetchone()[0]
        id_konsultasi = int(temp_id_konsultasi) + 1

        cursor_post.execute("SELECT COUNT(*) FROM SESI_KONSULTASI WHERE id_konsultasi ='" + str(id_konsultasi) + "'")
        if_existing = cursor_post.fetchone()[0]

        while (if_existing != 0):
            id_konsultasi = id_konsultasi + 1
            cursor_post.execute("SELECT COUNT(*) FROM SESI_KONSULTASI WHERE id_konsultasi ='" + str(id_konsultasi) + "'")
            if_existing = cursor_post.fetchone()[0]

        insertion = "INSERT INTO SESI_KONSULTASI VALUES(%s, %s, %s, %s, %s, %s);"
        cursor_post.execute(insertion, (str(id_konsultasi), no_rekam_medis_pasien, tanggal, str(biaya), status, id_transaksi))

        return redirect('/daftarkonsultasi/')
    
    return redirect('/login/')

def rscabang(request):
    if request.method == 'GET':
        form = RSCabangForm(request.POST)
        listform2 = RSCabang.objects.all()
        context = {
            'form' : form,
            'listform' : listform2,
        }
        return render(request, 'rscabang.html', context)
    
    elif request.method == 'POST':
        cursor_post = connection.cursor()
        kode_rs = request.POST.get('kode_rs')
        nama = request.POST["nama"]
        tanggal_pendirian = request.POST["tanggal_pendirian"]
        jalan = request.POST["jalan"]
        nomor = request.POST["nomor"]
        kota = request.POST["kota"]

        insertion = "INSERT INTO RS_CABANG VALUES(%s, %s, %s, %s, %s, %s);"
        cursor_post.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_post.execute(insertion, (kode_rs, nama, tanggal_pendirian, jalan, str(nomor), kota))

        return redirect('/daftarrscabang/')

    return redirect('/login/')

def updatekonsultasi(request, id):
    if request.method == 'POST':
        tanggal = request.POST.get('tanggal')
        status = request.POST.get('status')
        
        data = "UPDATE SESI_KONSULTASI SET tanggal=%s, status=%s WHERE id_konsultasi = '" + id + "'" + ";"
        cursor_update = connection.cursor()
        cursor_update.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_update.execute(data, (tanggal, status))
        
        return redirect('/daftarkonsultasi/')
    
    elif request.method == 'GET':
        form = UpdateKonsultasiForm(request.POST)
        listform = Konsultasi.objects.all()

        NRM = "SELECT no_rekam_medis_pasien FROM SESI_KONSULTASI WHERE id_konsultasi = '" + id + "'" + ";"
        biaya = "SELECT biaya FROM SESI_KONSULTASI WHERE id_konsultasi = '" + id + "'" + ";"
        IDT = "SELECT id_transaksi FROM SESI_KONSULTASI WHERE id_konsultasi = '" + id + "'" + ";"

        cursor_NRM = connection.cursor()
        cursor_biaya = connection.cursor()
        cursor_IDT = connection.cursor()

        cursor_NRM.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_biaya.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_IDT.execute('SET SEARCH_PATH TO MEDIKAGO;')

        cursor_NRM.execute(NRM)
        cursor_biaya.execute(biaya)
        cursor_IDT.execute(IDT)

        data_NRM = cursor_NRM.fetchone()[0]
        data_biaya = cursor_biaya.fetchone()[0]
        data_IDT = cursor_IDT.fetchone()[0]
        

        context = {
            'form' : form,
            'listform' : listform,
            'id_konsultasi': id,
            'data_NRM': data_NRM,
            'data_biaya': data_biaya,
            'data_IDT': data_IDT
        }

    return render(request, 'updatekonsultasi.html', context)

def updaterscabang(request, id):
    if request.method == 'POST':
        nama = request.POST.get('nama')
        tanggal_pendirian = request.POST.get('tanggal_pendirian')
        jalan = request.POST.get('jalan')
        nomor = request.POST.get('nomor')
        kota = request.POST.get('kota')
        
        data2 = "UPDATE RS_CABANG SET nama=%s, tanggal_pendirian=%s, jalan=%s, nomor=%s, kota=%s WHERE kode_rs = '" + id + "'" + ";"
        cursor_update = connection.cursor()
        cursor_update.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_update.execute(data2, (nama, tanggal_pendirian, jalan, str(nomor), kota))
    
        return redirect('/daftarrscabang/')

    elif request.method == 'GET':
        form = UpdateRSCabangForm(request.POST)
        listform = RSCabang.objects.all()

        RSC = "SELECT kode_rs FROM RS_CABANG WHERE kode_rs = '" + id + "'" + ";"
        cursor_RSC = connection.cursor()
        cursor_RSC.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor_RSC.execute(RSC)
        data_RSC = cursor_RSC.fetchone()[0]

        context = {
            'form' : form,
            'listform' : listform,
            'kode_rs':id
        }        

    return render(request, 'updaterscabang.html', context)

def daftarkonsultasi(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    cursor.execute('SELECT * FROM SESI_KONSULTASI;')
    data = namedtuplefetchall(cursor)
    return render(request, 'konsultasi2.html', {'data':data})

def daftarrscabang(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    cursor.execute('SELECT * FROM RS_CABANG;')
    data = namedtuplefetchall(cursor)
    return render(request, 'rscabang2.html', {'data':data})

def deletekonsultasi(request, id):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    cursor.execute("DELETE FROM SESI_KONSULTASI WHERE id_konsultasi='" + id + "'" + ";")
    return redirect('/daftarkonsultasi/')


def deleterscabang(request, id):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    cursor.execute("DELETE FROM RS_CABANG WHERE kode_rs= '" + id + "'" + ";")
    return redirect('/daftarrscabang/')

def loginregister(request):
    return render(request, 'loginregister.html')

def login(request): 
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        cursor_login = connection.cursor()
        cursor_login.execute("SELECT email, password FROM MEDIKAGO.PENGGUNA WHERE email= '" + email + "'" + ";")
        user = cursor_login.fetchone()

        if user is not None:
             if password == user[1]:
                request.session['username'] = username
                cursor_pasien = connection.cursor()
                cursor_pasien.execute("SELECT * FROM MEDIKAGO.PASIEN WHERE email= '" + email + "'" + ";")
                role_pasien = namedtuplefetchall(cursor_pasien)

                cursor_dokter = connection.cursor()
                cursor_dokter.execute("SELECT * FROM MEDIKAGO.DOKTER WHERE email= '" + email + "'" + ";")
                role_dokter = namedtuplefetchall(cursor_dokter)

                cursor_administrator = connection.cursor()
                cursor_administrator.execute("SELECT * FROM MEDIKAGO.ADMINISTRATOR WHERE email= '" + email + "'" + ";")
                role_administrator = namedtuplefetchall(cursor_administrator)
                
                if len(role_pasien) != 0:
                    request.session['role'] = 'pasien'
                elif len(role_dokter) != 0:
                    request.session['role'] = 'dokter'
                elif len(role_administrator) != 0:
                    request.session['role'] = 'administrator'
                return redirect('/login/homepage/')
    
    form = LoginForm(request.POST)
   
    context = {
        'form' : form,
    }

    return render(request, 'login.html', context)

def register(request):
    return render(request, 'register.html')

def administrator(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

konsultasicabang/templates/administrator.html
<!DOCTYPE html>
<html lang='en'>
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Form Pendaftaran Administrator</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/konsultasi.css' %}"> 
</head>

<body style="padding: 20px;">
	<div class = "bodykonsultasi">

		<div class="col-12 justify-content-center">
			<h1 class="d-flex justify-content-center">FORM PENDAFTARAN ADMINISTRATOR</h1> 
			<div class="text-center mt-4">
				<form method="POST" class="post-form">
					{% csrf_token %}
					{{ form.as_p }}
					<button id="submit" class="btn btn-outline-dark btn-lg">DAFTAR</button>
				</form>
			</div>
		</div>

	</div>
</body>
</html>

konsultasicabang/templates/konsultasi.html
<!DOCTYPE html>
<html lang='en'>
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Form Sesi Konsultasi</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/konsultasi.css' %}"> 



	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body style="padding: 20px;">
	<div class = "bodykonsultasi">

		<nav class="navbar navbar-expand-sm navigation">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'konsultasicabang:konsultasi' %}">Buat Sesi Konsultasi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'konsultasicabang:rscabang' %}">Buat RS Cabang</a>
                </li>
                <li class="nav-item">
					<a class="nav-link" href="{% url 'konsultasicabang:daftarkonsultasi' %}">Daftar Sesi Konsultasi</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'konsultasicabang:daftarrscabang' %}">Daftar RS Cabang</a>
				</li>
            </ul>
        </nav>

		<div class="col-12 justify-content-center">
			<h1 class="d-flex justify-content-center">FORM RESERVASI SESI KONSULTASI</h1> 
			<div class="text-center mt-4">
				<form method="POST" class="post-form">
					{% csrf_token %}
					
					<label for="no_rekam_medis_pasien">No Rekam Medis:</label>
					<select id="no_rekam_medis_pasien" name="no_rekam_medis_pasien">
						<option value="none">none</option>
						{% for item in data1 %}
						<option value={{item.no_rekam_medis_pasien}}>{{item.no_rekam_medis_pasien}}</option>
						{% endfor %}
					</select>

					<label for="tanggal">Tanggal:</label>
					{{ form.tanggal }}

					<label for="id_transaksi">ID Transaksi:</label>
					<select id='id_transaksi' name="id_transaksi">
						<option value="none">none</option>
						{% for item in data2 %}
						<option value={{item.id_transaksi}}>{{item.id_transaksi}}</option>
						{% endfor %}
					</select>

					<button id="submit" class="btn btn-outline-dark btn-lg">SUBMIT</button>
				</form>
			</div>
		</div>

	</div>
</body>
</html>

konsultasicabang/templates/konsultasi2.html
<!DOCTYPE html>
<html lang='en'>
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Daftar Sesi Konsultasi</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/konsultasi.css' %}"> 
</head>

<body style="padding: 20px;">
	<div class = "bodykonsultasi">

        <nav class="navbar navbar-expand-sm navigation">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'konsultasicabang:konsultasi' %}">Buat Sesi Konsultasi</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'konsultasicabang:rscabang' %}">Buat RS Cabang</a>
                </li>
                <li class="nav-item">
					<a class="nav-link" href="{% url 'konsultasicabang:daftarkonsultasi' %}">Daftar Sesi Konsultasi</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'konsultasicabang:daftarrscabang' %}">Daftar RS Cabang</a>
				</li>
            </ul>
        </nav>
        
		<div class="col-12 justify-content-center">
			<h1 class="d-flex justify-content-center">SESI KONSULTASI</h1> 
        
            <div class="table-responsive my-8 px-4 py-2">
                <table class="table table-active table-striped table_custom">
                  <thead>
                    <tr>
                        <th scope="col" class="header one">ID Konsultasi</th>
                        <th scope="col" class="header two">Nomor Pasien</th>
                        <th scope="col" class="header three">Tanggal</th>
                        <th scope="col" class="header four">Biaya</th>
                        <th scope="col" class="header five">Status</th>
                        <th scope="col" class="header six">ID Transaksi</th>
                        <th scope="col" class="header seven">Action[admin]</th>

                    </tr>
                  </thead>
                  <tbody>
                      {% for isi in data %}
                      <tr>
                        <td class="stylekonsultasi">{{ isi.id_konsultasi }}</td>
                        <td class="stylekonsultasi">{{ isi.no_rekam_medis_pasien }}</td>
                        <td class="stylekonsultasi">{{ isi.tanggal }}</td>
                        <td class="stylekonsultasi">{{ isi.biaya }}</td>
                        <td class="stylekonsultasi">{{ isi.status }}</td>
                        <td class="stylekonsultasi">{{ isi.id_transaksi }}</td>
                        <td class="stylekonsultasi">
                            <a class="btn btn-primary" href="/updatekonsultasi/{{ isi.id_konsultasi }}">Update</a>
                            <a class="btn btn-primary" href="/deletekonsultasi/{{ isi.id_konsultasi }}">Delete</a>
                        </td>
                      </tr>
                      {% endfor %}
                  </tbody>
          
                </table>
            </div>

		</div>

	</div>
</body>
</html>

konsultasicabang/templates/rscabang.html
<!DOCTYPE html>
<html lang='en'>
<head>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Form Pembuatan RS Cabang</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/konsultasi.css' %}"> 
</head>

<body style="padding: 20px;">

	<nav class="navbar navbar-expand-sm navigation">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'konsultasicabang:konsultasi' %}">Buat Sesi Konsultasi</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'konsultasicabang:rscabang' %}">Buat RS Cabang</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'konsultasicabang:daftarkonsultasi' %}">Daftar Sesi Konsultasi</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'konsultasicabang:daftarrscabang' %}">Daftar RS Cabang</a>
			</li>
		</ul>
	</nav>


	<div class = "bodykonsultasi">
		
		<div class="col-12 justify-content-center">
			<h1 class="d-flex justify-content-center">FORM PEMBUATAN RS CABANG</h1> 
			<div class="text-center mt-4">
				<form method="POST" class="post-form">
					{% csrf_token %}
					{{ form.as_p }}
					<button id="submit" class="btn btn-outline-dark btn-lg">SUBMIT</button>
				</form>
			</div>
		</div>

	</div>
</body>
</html>