basdat/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include,path
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ungu.urls')),
    path('', include('hijau.urls')),
    path('', include('konsultasicabang.urls')),
    path('', include('transaksi.urls'))
]

ungu/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('daftar-dokter-rs-cabang', views.daftardokterrs, name='daftarDokterRs'),

    path('rud-dokter-rs', views.rudDokterRs, name='rudDokterRs'),
    path('rud-dokter-rs-admin', views.rudDokterRsAdmin, name='rudDokterRsAdmin'),
    path('dok-rs/update', views.dokRsUpdate, name='dokRsUpdate'),
    path('dok-rs/delete', views.dokRsDelete, name='dokRsDelete'),


    path('layanan-jadwal-poli', views.layananJadwalPoli, name='layananJadwalPoli'),
    path('layanan-jadwal-poli-admin', views.layananJadwalPoliAdmin, name='layananJadwalPoliAdmin'),
    path('orderPoli/pesan', views.orderPoli, name='orderPoli'),
    path('orderPoli-admin/pesan', views.orderPoliAdmin, name='orderPoliAdmin'),
    path('poli/update', views.updateLayananPoliklinik, name='updateLayananPoliklinik'),
    path('poli/delete', views.deleteLayananPoliklinik, name='deleteLayananPoliklinik'),
    path('orderPoli-admin/jadwal/update', views.updateJadwalPoliklinik, name='updateJadwalPoliklinik'),
    path('orderPoli-admin/jadwal/delete', views.deleteJadwalPoliklinik, name='deleteJadwalPoliklinik')
]

ungu/models.py
from django.db import models

# Create your models here.
class Dokter_RsCabang(models.Model):
    id_dokter = id_dokter = models.CharField(max_length=50)
    kode_rs = kode_rs = models.CharField(max_length=50)

class LayananPoliklinik(models.Model):
    id_poliklinik = models.CharField(max_length=50, primary_key= True)
    nama_layanan = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=50)
    rs_cabang = models.CharField(max_length=50)

    def getId(self):
        return str(self.id_poliklinik)
    def getNama(self):
        return str(self.nama_layanan)
    def getDesc(self):
        return str(self.deskripsi)
    def getRs(self):
        return str(self.rs_cabang)

class UpdateLayananPoliklinik(models.Model):
    rs_cabang = models.CharField(max_length=50)

class UpdateJadwalLayananPoliklinik(models.Model):
    rs_cabang = models.CharField(max_length=50)

class JadwalLayananPoliklinik(models.Model):
    id_jadwal_poliklinik = models.CharField(max_length=50, default="", primary_key= True)
    waktu_mulai = models.CharField(max_length=50, default="")
    waktu_selesai = models.CharField(max_length=50, default="")
    hari = models.CharField(max_length=50, default="")
    kapasitas = models.CharField(max_length=50, default="")
    id_dokter = models.CharField(max_length=50, default="")
    id_poliklinik = models.CharField(max_length=50, default="")

    def getIdJadwalPoliklinik(self):
        return str(self.id_jadwal_poliklinik)
    def getWaktuMulai(self):
        return str(self.waktu_mulai)
    def getWaktuSelesai(self):
        return str(self.waktu_selesai)
    def getHari(self):
        return str(self.hari)
    def getKapasitas(self):
        return str(self.kapasitas)
    def getIdDokter(self):
        return str(self.id_dokter)
    def getIdPoliklinik(self):
        return str(self.id_poliklinik)

ungu/forms.py
from django import forms
from .models import *
import datetime

class FormDaftarDokterRsCabang(forms.ModelForm):
    id_dokter = forms.ChoiceField(choices=
    [('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7')
    ])

    kode_rs = forms.ChoiceField(choices=
    [('1001', '1001'),
    ('1002', '1002'),
    ('1003', '1003'),
    ('1004', '1004'),
    ('1005', '1005')
    ])

    class Meta:
        model = Dokter_RsCabang
        fields = {
            'id_dokter',
            'kode_rs'
            }

class FormUpdateLayananPoliklinik(forms.ModelForm):
    rs_cabang = forms.ChoiceField(choices=[
        ('200001', '20001'),
        ('200002', '20002'),
        ('200003', '20003'),
        ('200004', '20004'),
        ('200005', '20005'),
    ]
    )
    
    class Meta:
        model = UpdateLayananPoliklinik
        fields = {
            'rs_cabang'
        }

class FormUpdateJadwalLayananPoliklinik(forms.ModelForm):
    id_dokter = forms.ChoiceField(choices=[
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7')
    ])

    class Meta:
        model = UpdateJadwalLayananPoliklinik
        fields = {
            'id_dokter'
        }

ungu/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from ungu.forms import *
from ungu.models import *
from django.db import connection
from collections import namedtuple


# Create your views here.

def namedtuplefetchall(cursor):
    # "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def daftardokterrs(request):
    if request.method == "GET":
        form = FormDaftarDokterRsCabang(request.GET)
        return render(request, 'daftar-dokter-rs.html', {"form" : form})
    elif request.method == "POST":
        form = FormDaftarDokterRsCabang(request.POST)
        if form.is_valid():
            id_dokter = form.cleaned_data["id_dokter"]
            kode_rs = form.cleaned_data["kode_rs"]
            cursor = connection.cursor()
            cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
            insert = 'INSERT INTO MEDIKAGO.DOKTER_RS_CABANG VALUES (%s, %s)'
            cursor.execute(insert, (id_dokter, kode_rs))
            return redirect("rudDokterRsAdmin")

def rudDokterRsAdmin(request):
    cursor1 = connection.cursor()
    cursor2 = connection.cursor()
    cursor1.execute('SET SEARCH_PATH TO MEDIKAGO;')
    cursor2.execute('SET SEARCH_PATH TO MEDIKAGO;')

    kode_rs_list_com = 'SELECT kode_rs FROM DOKTER_RS_CABANG;'
    kode_rs_list_with_dok_com = 'SELECT kode_rs, id_dokter FROM DOKTER_RS_CABANG;'

    cursor1.execute(kode_rs_list_com)
    cursor2.execute(kode_rs_list_with_dok_com)

    data1 = namedtuplefetchall(cursor1)
    data2 = namedtuplefetchall(cursor2)

    listOList = {}
    for i in data1:
        if i[0] in listOList:
            continue
        else:
            listOList[i[0]] = [j[1] for j in data2 if j[0] == i[0]]

    #listOfList = { "100001" : ["1", "4"], "100002" : ["2", "7"], "100003" : ["3", "2"], "100004" : ["4", "6"], "100005" : ["5", "1"] }
    return render(request, 'RUD-dokter-rs-admin.html', {"rsList" : listOList})

def rudDokterRs(request):
    cursor1 = connection.cursor()
    cursor2 = connection.cursor()
    cursor1.execute('SET SEARCH_PATH TO MEDIKAGO;')
    cursor2.execute('SET SEARCH_PATH TO MEDIKAGO;')

    kode_rs_list_com = 'SELECT kode_rs FROM DOKTER_RS_CABANG;'
    kode_rs_list_with_dok_com = 'SELECT kode_rs, id_dokter FROM DOKTER_RS_CABANG;'

    cursor1.execute(kode_rs_list_com)
    cursor2.execute(kode_rs_list_with_dok_com)

    data1 = namedtuplefetchall(cursor1)
    data2 = namedtuplefetchall(cursor2)

    listOList = {}
    for i in data1:
        if i[0] in listOList:
            continue
        else:
            listOList[i[0]] = [j[1] for j in data2 if j[0] == i[0]]
    #listOfList = { "100001" : ["1", "4"], "100002" : ["2", "7"], "100003" : ["3", "2"], "100004" : ["4", "6"], "100005" : ["5", "1"] }
    return render(request, 'RUD-dokter-rs.html', {"rsList" : listOList})


def dokRsUpdate(request):
    if request.method == 'GET':
        idRs = request.GET['rs']
        idDoc = request.GET['doc']
        cursor1 = connection.cursor()
        cursor2 = connection.cursor()
        cursor1.execute('SET SEARCH_PATH TO MEDIKAGO;')
        cursor2.execute('SET SEARCH_PATH TO MEDIKAGO;')

        kode_rs_list_com = 'SELECT id_dokter FROM DOKTER;'
        id_dok_list_com = 'SELECT kode_rs FROM RS_CABANG;'

        cursor1.execute(kode_rs_list_com)
        cursor2.execute(id_dok_list_com)

        data1 = namedtuplefetchall(cursor1)
        data2 = namedtuplefetchall(cursor2)
        listDoctors = [i[0] for i in data1]
        listRs = [i[0] for i in data2]

        if idRs in listRs:
            listRs.remove(idRs)
        if idDoc in listDoctors:
            listDoctors.remove(idDoc)
        return render(request, 'update-dokter-rs.html', {"idRs" : idRs, "idDoc" : idDoc, "listDoctors" : listDoctors, "listRs" : listRs})

def dokRsDelete(request):
    return redirect('rudDokterRs')

def layananJadwalPoli(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    layanan_poliklinik = 'SELECT id_poliklinik, nama, deskripsi, kode_rs_cabang FROM LAYANAN_POLIKLINIK;'
    cursor.execute(layanan_poliklinik)
    data = namedtuplefetchall(cursor)

    listOfPolikliniks = {}
    for i in data:
        listOfPolikliniks[i[0]] = [i[1], i[2], i[3]]
    #listOfPolikliniks = {
    #    "200001" : ["Orthopedic", "Menangani masalah tulang", "100004"],
    #    "200002" : ["Psychiatry", "Menangani masalah mental", "100005"],
    #    "200003" : ["Interna", "Menangani masalah penyakit dalam", "100001"],
    #    "200004" : ["Obgyn", "Menangani masalah kehamilan", "100003"],
    #    "200005" : ["Neurology", "Menangani masalah syaraf", "100002"]
    #}
    return render(request, 'layanan-jadwal-poliklinik.html', {"list" : listOfPolikliniks})

def layananJadwalPoliAdmin(request):
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    layanan_poliklinik = 'SELECT id_poliklinik, nama, deskripsi, kode_rs_cabang FROM LAYANAN_POLIKLINIK;'
    cursor.execute(layanan_poliklinik)
    data = namedtuplefetchall(cursor)

    listOfPolikliniks = {}
    for i in data:
        listOfPolikliniks[i[0]] = [i[1], i[2], i[3]]
    #listOfPolikliniks = {
    #    "200001" : ["Orthopedic", "Menangani masalah tulang", "100004"],
    #    "200002" : ["Psychiatry", "Menangani masalah mental", "100005"],
    #    "200003" : ["Interna", "Menangani masalah penyakit dalam", "100001"],
    #    "200004" : ["Obgyn", "Menangani masalah kehamilan", "100003"],
    #    "200005" : ["Neurology", "Menangani masalah syaraf", "100002"]
    #}
    return render(request, 'layanan-jadwal-poliklinik-admin.html', {"list" : listOfPolikliniks})

def orderPoli(request):
    kodePoli = request.GET['kodePoli']
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    jadwal_poli = 'SELECT * FROM JADWAL_LAYANAN_POLIKLINIK WHERE id_poliklinik=' + kodePoli + ';'
    cursor.execute(jadwal_poli)
    listOfSched = namedtuplefetchall(cursor)
    return render(request, "jadwal-poliklinik.html", { "listOfSched" : listOfSched })

def orderPoliAdmin(request):
    kodePoli = request.GET['kodePoli']
    cursor = connection.cursor()
    cursor.execute('SET SEARCH_PATH TO MEDIKAGO;')
    jadwal_poli = 'SELECT * FROM JADWAL_LAYANAN_POLIKLINIK WHERE id_poliklinik=' + kodePoli + ';'
    cursor.execute(jadwal_poli)
    listOfSched = namedtuplefetchall(cursor)
    return render(request, "jadwal-poliklinik-admin.html", { "listOfSched" : listOfSched })

def updateLayananPoliklinik(request):
    #listOfPolikliniks = {
    #    "200001" : ["Orthopedic", "Menangani masalah tulang", "100004"],
    #    "200002" : ["Psychiatry", "Menangani masalah mental", "100005"],
    #    "200003" : ["Interna", "Menangani masalah penyakit dalam", "100001"],
    #    "200004" : ["Obgyn", "Menangani masalah kehamilan", "100003"],
    #    "200005" : ["Neurology", "Menangani masalah syaraf", "100002"]
    #}
    #for i in listOfPolikliniks:
    #    a = LayananPoliklinik(
    #        id_poliklinik= i,
    #        nama_layanan=listOfPolikliniks.get(i)[0],
    #        deskripsi=listOfPolikliniks.get(i)[1],
    #        rs_cabang=listOfPolikliniks.get(i)[2]
    #        )
    #    a.save()
    if request.method == 'GET':
        id_poliklinik = request.GET["kodePoli"]
        cursor1 = connection.cursor()
        cursor1.execute('SET SEARCH_PATH TO MEDIKAGO;')
        jadwal_poli = 'SELECT * FROM JADWAL_LAYANAN_POLIKLINIK WHERE id_poliklinik=' + id_poliklinik + ';'
        cursor1.execute(jadwal_poli)
        poliklinik = namedtuplefetchall(cursor1)

        cursor2 = connection.cursor()
        cursor2.execute('SET SEARCH_PATH TO MEDIKAGO;')
        kode_rs = 'SELECT kode_rs FROM RS_CABANG;'
        cursor2.execute(kode_rs)
        listKodeRs = namedtuplefetchall(cursor2)
        
        #poliklinik = LayananPoliklinik.objects.get(id_poliklinik=id_poliklinik)
        #print(poliklinik.getId())
        form = FormUpdateLayananPoliklinik(request.GET)
        return render(request, 'update-layanan-poliklinik.html', { "listKodeRs" : listKodeRs, "poliklinik" : poliklinik, "form" : form})
    elif request.method == 'POST':
        data = request.POST.copy()
        return redirect('layananJadwalPoli')

def deleteLayananPoliklinik(request):
    # TODO update database
    return redirect('layananJadwalPoli')

def updateJadwalPoliklinik(request):
    if request.method == 'GET':
        id_jadpol = request.GET['idJadwalPoli']
        jadPol = JadwalLayananPoliklinik.objects.get(id_jadwal_poliklinik=id_jadpol)
        form = FormUpdateJadwalLayananPoliklinik(request.GET)
        return render(request, "update-jadwal-layanan-poliklinik.html", {"jadPol" : jadPol, "form" : form})
    elif request.method == 'POST':
        return redirect('layananJadwalPoli')

def deleteJadwalPoliklinik(request):
    # TODO update database
    return redirect('layananJadwalPoli')

ungu/templates/RUD-dokter-rs-admin.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Dokter - RS Cabang</title>
  </head>
  <body>
    <h1>Dokter - RS Cabang</h1>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Kode RS Cabang</th>
            <th scope="col">ID Dokter</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
            {% for rs in rsList %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ rs }}</td>
            <td>
                <ul class="list-group">
                    {% for key, value in rsList.items %}
                        {% if key == rs %}
                            {% for doc in value %}
                                <li class="list-group-item">{{ doc }}</li>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul class="list-group">
                    {% for key, value in rsList.items %}
                    {% if key == rs %}
                        {% for doc in value %}
                            <a href="dok-rs/update?rs={{rs}}&doc={{doc}}">update</a>
                            <a href="dok-rs/delete?rs={{rs}}&doc={{doc}}">delete</a>
                        {% endfor %}
                        {% endif %}
                    {% endfor %}
                </ul>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ungu/templates/RUD-dokter-rs.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Dokter - RS Cabang</title>
  </head>
  <body>
    <h1>Dokter - RS Cabang</h1>
    <table class="table">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Kode RS Cabang</th>
            <th scope="col">ID Dokter</th>
          </tr>
        </thead>
        <tbody>
            {% for rs in rsList %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ rs }}</td>
            <td>
                <ul class="list-group">
                    {% for key, value in rsList.items %}
                    {% if key == rs %}
                    {% for doc in value %}
                    <li class="list-group-item">{{ doc }}</li>
                    {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ungu/templates/daftar-dokter-rs.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>FORM PENDAFTARAN DOKTER RS CABANG</title>
  </head>
  <body>
    <h1>FORM PENDAFTARAN DOKTER RS CABANG</h1>
    <form method="post" actions="/submit-daftar-dokter-rs/">
        {% csrf_token%}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

ungu/templates/update-layanan-poliklinik.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>FORM UPDATE LAYANAN POLIKLINIK</title>
  </head>
  <body>
    <h1>FORM UPDATE LAYANAN POLIKLINIK</h1>
    <p>ID Poliklinik: {{ poliklinik.id_poliklinik }}</p>
    <p>Nama: {{ poliklinik.nama }}</p>
    <p>Deskripsi: {{ poliklinik.deskripsi }}</p>
    <form method="post" actions="/submit-daftar-dokter-rs/">
        {% csrf_token%}
        <p hidden>
            <label for='id_id_poliklinik'></label>
            <input value='{{ poliklinik.getId }}'>
        </p>
        <p>
            <label for='id_rs_cabang'>RS Cabang</label>
            <select id='id_rs_cabang' name='rs_cabang'>
              {% for kode in listKodeRs %}
                <option value="200001">{{ kode }}</option>
              {% endfor %}
            </select>
        </p>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>